### ISSUE TITLE
FAQ Section accordion bug

### ISSUE THREAD

**Issue by majordwarf** [ramanaditya/Microsoft-Student-Partners#33]
**Describe the bug**
In the FAQ section, the last three questions, when licked will toggle the opening and closing of 4th last question.

**To Reproduce**
1. Go to the website
2. Scroll down to FAQ Section
3. Click on any last 3 questions

**Expected behaviour**
The question should toggle their answers instead of the 4th last question.

**Comment by ramanaditya** [comment]
The issue be resolved in the next release, It has been fixed.
