### ISSUE TITLE
Overflow in x

### ISSUE THREAD

**Issue by ramanaditya** [ramanaditya/Microsoft-Student-Partners#86]
**Describe the bug**
Overflow in x is observed when the website is opened in the mobile.

**Expected behaviour**
You need to fix that so that the scrolling can only be done along the y-axis.

**Comment by samjain2907** [comment]
@ramanaditya Can I work on this one?

**Comment by ramanaditya** [comment]
@samjain2907 , yeah sure you can work on this and post is as soon as possible because if anyone will send us the PR before you, then we won't be able to merge your code.
